language: ruby
os: linux
cache: bundler
before_install:
  gem update bundler
install:
  - bundle config set path 'vendor/bundle'
  - bundle install --jobs=3 --retry=3
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
env:
  - COVERAGE=1
jobs:
  fast_finish: true
