version: 2.1
references:
  default: &default
      steps:
        - checkout
        - run: gem update bundler
        - restore_cache:
            keys:
              - tidy-json-{{ checksum "Gemfile" }}
              - tidy-json-
        - run: bundle config set path 'vendor/bundle'
        - run: bundle install --jobs=3 --retry=3
        - run: bundle clean
        - save_cache:
            key: tidy-json-{{ checksum "Gemfile" }}
            paths:
              - vendor/bundle
        - run:
            name: Test gem
            environment:
              COVERAGE: 1
            command: bundle exec rake

jobs:
  rb23:
    docker:
      - image: circleci/ruby:2.3-stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    <<: *default
  rb24:
    docker:
      - image: circleci/ruby:2.4-buster
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    <<: *default
  rb25:
    docker:
      - image: circleci/ruby:2.5-buster
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    <<: *default
  rb26:
    docker:
      - image: circleci/ruby:2.6-buster
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    <<: *default
  rb27:
    docker:
      - image: circleci/ruby:2.7-buster
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    <<: *default
  rb30:
    docker:
      - image: circleci/ruby:3.0-buster
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    <<: *default

workflows:
  test_all_rubies:
    jobs:
      - rb23:
          context:
            - docker-hub-creds
      - rb24:
          context:
            - docker-hub-creds
      - rb25:
          context:
            - docker-hub-creds
      - rb26:
          context:
            - docker-hub-creds
      - rb27:
          context:
            - docker-hub-creds
      - rb30:
          context:
            - docker-hub-creds
