version: 2.1
references:
  default: &default
      steps:
        - checkout
        - run: gem update bundler
        - restore_cache:
            keys:
              - tidy-json-{{ checksum "Gemfile" }}
              - tidy-json-
        - run: bundle config set path 'vendor/bundle'
        - run: bundle install --jobs=3 --retry=3
        - run: bundle clean
        - save_cache:
            key: tidy-json-{{ checksum "Gemfile" }}
            paths:
              - vendor/bundle
        - run:
            name: Test gem
            environment:
              COVERAGE: 1
            command: bundle exec rake

  releases-only: &releases-only
    filters:
      tags:
        only: /^v(\d*\.)+\d*$/
      branches:
        ignore: /.*/

  docker-login: &docker-login
    auth:
      username: $DOCKERHUB_USER
      password: $DOCKERHUB_PASSWORD

jobs:
  rb23:
    docker:
      - image: circleci/ruby:2.3-stretch
        <<: *docker-login
    <<: *default
  rb24:
    docker:
      - image: circleci/ruby:2.4-buster
        <<: *docker-login
    <<: *default
  rb25:
    docker:
      - image: circleci/ruby:2.5-buster
        <<: *docker-login
    <<: *default
  rb26:
    docker:
      - image: circleci/ruby:2.6-buster
        <<: *docker-login
    <<: *default
  rb27:
    docker:
      - image: circleci/ruby:2.7-buster
        <<: *docker-login
    <<: *default
  rb30:
    docker:
      - image: circleci/ruby:3.0-buster
        <<: *docker-login
    <<: *default

workflows:
  test_all_rubies:
    jobs:
      - rb23:
          context:
            - docker-hub-creds
          <<: *releases-only
      - rb24:
          context:
            - docker-hub-creds
          <<: *releases-only
      - rb25:
          context:
            - docker-hub-creds
          <<: *releases-only
      - rb26:
          context:
            - docker-hub-creds
          <<: *releases-only
      - rb27:
          context:
            - docker-hub-creds
          <<: *releases-only
      - rb30:
          context:
            - docker-hub-creds
          <<: *releases-only
