build-gem: &build_gem
      - run:
          name: Update bundler
          command: gem update bundler
      - restore_cache:
          keys:
            - tidy-json-{{ checksum "Gemfile.lock" }}
            - tidy-json-
      - run:
          name: Set bundler path
          command: bundle config set path 'vendor/bundle'
      - run:
          name: Install gems
          command: bundle install --jobs=3 --retry=3
      - save_cache:
          key: tidy-json-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Test gem
          command: bundle exec rake
      - store_test_results:
          path: test_results

version: 2

jobs:
  rb23:
    docker:
      - image: circleci/ruby:2.3-stretch
    steps:
      - checkout
    <<: *build_gem
  rb24:
    docker:
      - image: circleci/ruby:2.4-buster
    steps:
      - checkout
    <<: *build_gem
  rb25:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
    <<: *build_gem
  rb26:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
    <<: *build_gem
  rb27:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
    <<: *build_gem

workflows:
 version: 2
 multi_ruby_build:
   jobs:
     - rb23
     - rb24
     - rb25
     - rb26
     - rb27
