version: 2
references:
  default: &default
      steps:
        - checkout
        - run: gem update bundler
        - restore_cache:
            keys:
              - tidy-json-{{ checksum "Gemfile" }}
              - tidy-json-
        - run: bundle config set path 'vendor/bundle'
        - run: bundle install --jobs=3 --retry=3
        - run: bundle clean
        - save_cache:
            key: tidy-json-{{ checksum "Gemfile" }}
            paths:
              - vendor/bundle
        - run:
            name: Test gem
            command: bundle exec rake

jobs:
  rb23:
    docker:
      - image: circleci/ruby:2.3-stretch
    <<: *default
  rb24:
    docker:
      - image: circleci/ruby:2.4-buster
    <<: *default
  rb25:
    docker:
      - image: circleci/ruby:2.5
    <<: *default
  rb26:
    docker:
      - image: circleci/ruby:2.6
    <<: *default
  rb27:
    docker:
      - image: circleci/ruby:2.7
    <<: *default

workflows:
  version: 2
  test_all_rubies:
    jobs:
      - rb23
      - rb24
      - rb25
      - rb26
      - rb27
